name: Notify on Issue Creation
on:
  issues:
    types: [opened]

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Send email notification
      uses: dawidd6/action-send-mail@v2
      with:
        # You need to set these secrets in your repository settings
        server_address: smtp.example.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: New Issue in Your Repository
        # Customize the body as needed
        body: An issue has been opened in your repository. Check it out!
        to: your-email@example.com
        from: GitHub Actions <noreply@example.com>
